In [3]:
print("hello world")

hello world

In [8]:
%pip install numpy
%pip install pandas
%pip install scikit-learn
%pip install matplotlib
%pip install seaborn
%pip install --upgrade pip
%pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\Python314\Lib\site-packages (26.1.1)
Collecting pip
  Downloading pip-26.1.2-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.1.2-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------- ---------------------- 0.8/1.8 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 10.1 MB/s  0:00:00
Installing collected packages: pip
Successfully installed pip-26.1.2
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.5.9-cp314-cp314-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.68.2)
Requirement already satisfied: colorama in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.6 MB 6.5 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.6 MB 3.4 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.1 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 1.5 MB/s  0:00:00
Downloading regex-2026.5.9-cp314-cp314-win_amd64.whl (280 kB)
Installing collected packages: regex, nltk

   ---------------------------------------- 0/2 [regex]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed nltk-3.9.4 regex-2026.5.9
Note: you may need to restart the kernel to use updated packages.

In [9]:
## importing necessary libraries
import numpy as np ##for numerical computations
import pandas as pd ## Data manipulation and analysis
import matplotlib.pyplot as plt ## for data visualization
%matplotlib inline 

#importing wordcloud for text visualization
try:
    from wordcloud import WordCloud
except ImportError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "wordcloud"])
    from wordcloud import WordCloud
# importing NLTK for natural language priocessing tasks
import nltk
from nltk.corpus import stopwords #for stopwords data 
 ## downlaoding NLTK data
nltk.download('stopwords') #downloading stopwords data
nltk.download('punkt') #downloading punkt data for tokenization

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [10]:
# Read the CSV file
df=pd.read_csv('spam.csv')
#Display the first few rows of the dataset
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [11]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
## rename the columns for better understanding
df.rename(columns={'v1':'target','v2':'text'}, inplace=True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

Data Preprocessing

In [13]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [17]:
# checking for the duplicate values in the dataset
x=df.duplicated().sum()
print(f"Number of duplicate rows: {x}")
df.shape

Number of duplicate rows: 403

(5572, 2)

In [18]:
# remove the duolicate values from the dataset
df = df.drop_duplicates(keep='first')
len(df)

5169

Feature Engineering

In [19]:
#importing the porter stemmer for stemming the text data
from nltk.stem import PorterStemmer
#import the string library for string manipulation
import string
stemmer = PorterStemmer()

In [27]:
# Lowercase transformation and text preprocessing function
def transform_text( text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenization using NLTK
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
        
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    for i in text:
        y.append(stemmer.stem(i))
    
    # Join the processed tokens back into a single string
    return " ".join(y)

In [ ]:
import sys
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import string
!{sys.executable} -m pip install --upgrade pip
!{sys.executable} -m pip install nltk wordcloud
nltk.download('stopwords')
nltk.download('punkt')
stemmer = PorterStemmer()

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (26.1.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (3.9.4)
Requirement already satisfied: wordcloud in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (1.9.6)
Requirement already satisfied: click in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.68.2)
Requirement already satisfied: numpy>=1.19.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from wordcloud) (2.4.6)
Requirement already satisfied: pillow in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from wordcloud) (12.2.0)
Requirement already satisfied: matplotlib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from wordcloud) (3.11.0)
Requirement already satisfied: colorama in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (26.2)
Requirement already satisfied: pyparsing>=3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [33]:
## transform the text data 
transform_text('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - 'C:\\Users\\DELL/nltk_data'
    - 'c:\\Python314\\nltk_data'
    - 'c:\\Python314\\share\\nltk_data'
    - 'c:\\Python314\\lib\\nltk_data'
    - 'C:\\Users\\DELL\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************